//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDGenerator.SaIDValidator {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://xml-fx.com/services/SAIDValidator/", ConfigurationName="SaIDValidator.SAIDValidatorSoap")]
    public interface SAIDValidatorSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://xml-fx.com/services/SAIDValidator/GetServiceIdentifier", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetServiceIdentifier();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://xml-fx.com/services/SAIDValidator/GetServiceIdentifier", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetServiceIdentifierAsync();
        
        // CODEGEN: Generating message contract since message part namespace (http://xml-fx.com/services/SAIDValidator/said.xsd) does not match the default value (http://xml-fx.com/services/SAIDValidator/)
        [System.ServiceModel.OperationContractAttribute(Action="http://xml-fx.com/services/SAIDValidator/ValidateIdString", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="said")]
        IDGenerator.SaIDValidator.ValidateIdStringResponse ValidateIdString(IDGenerator.SaIDValidator.ValidateIdStringRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://xml-fx.com/services/SAIDValidator/ValidateIdString", ReplyAction="*")]
        System.Threading.Tasks.Task<IDGenerator.SaIDValidator.ValidateIdStringResponse> ValidateIdStringAsync(IDGenerator.SaIDValidator.ValidateIdStringRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml-fx.com/services/SAIDValidator/said.xsd")]
    public partial class saidType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string inputField;
        
        private saidTypeOutput outputField;
        
        private bool validField;
        
        private bool validFieldSpecified;
        
        private uint errorField;
        
        private bool errorFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Input {
            get {
                return this.inputField;
            }
            set {
                this.inputField = value;
                this.RaisePropertyChanged("Input");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public saidTypeOutput output {
            get {
                return this.outputField;
            }
            set {
                this.outputField = value;
                this.RaisePropertyChanged("output");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Valid {
            get {
                return this.validField;
            }
            set {
                this.validField = value;
                this.RaisePropertyChanged("Valid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValidSpecified {
            get {
                return this.validFieldSpecified;
            }
            set {
                this.validFieldSpecified = value;
                this.RaisePropertyChanged("ValidSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("Error");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ErrorSpecified {
            get {
                return this.errorFieldSpecified;
            }
            set {
                this.errorFieldSpecified = value;
                this.RaisePropertyChanged("ErrorSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xml-fx.com/services/SAIDValidator/said.xsd")]
    public partial class saidTypeOutput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int cCDField;
        
        private int cdField;
        
        private saidTypeOutputCitizen citizenField;
        
        private System.DateTime dOBField;
        
        private string errorFlagsField;
        
        private saidTypeOutputGender genderField;
        
        private string parsedField;
        
        private uint sequenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int CCD {
            get {
                return this.cCDField;
            }
            set {
                this.cCDField = value;
                this.RaisePropertyChanged("CCD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int CD {
            get {
                return this.cdField;
            }
            set {
                this.cdField = value;
                this.RaisePropertyChanged("CD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public saidTypeOutputCitizen Citizen {
            get {
                return this.citizenField;
            }
            set {
                this.citizenField = value;
                this.RaisePropertyChanged("Citizen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=3)]
        public System.DateTime DOB {
            get {
                return this.dOBField;
            }
            set {
                this.dOBField = value;
                this.RaisePropertyChanged("DOB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ErrorFlags {
            get {
                return this.errorFlagsField;
            }
            set {
                this.errorFlagsField = value;
                this.RaisePropertyChanged("ErrorFlags");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public saidTypeOutputGender Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
                this.RaisePropertyChanged("Gender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Parsed {
            get {
                return this.parsedField;
            }
            set {
                this.parsedField = value;
                this.RaisePropertyChanged("Parsed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public uint Sequence {
            get {
                return this.sequenceField;
            }
            set {
                this.sequenceField = value;
                this.RaisePropertyChanged("Sequence");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xml-fx.com/services/SAIDValidator/said.xsd")]
    public enum saidTypeOutputCitizen {
        
        /// <remarks/>
        Unknown,
        
        /// <remarks/>
        SA,
        
        /// <remarks/>
        Foreign,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xml-fx.com/services/SAIDValidator/said.xsd")]
    public enum saidTypeOutputGender {
        
        /// <remarks/>
        Unknown,
        
        /// <remarks/>
        Female,
        
        /// <remarks/>
        Male,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidateIdString", WrapperNamespace="http://xml-fx.com/services/SAIDValidator/", IsWrapped=true)]
    public partial class ValidateIdStringRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xml-fx.com/services/SAIDValidator/", Order=0)]
        public string authToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xml-fx.com/services/SAIDValidator/", Order=1)]
        public string said;
        
        public ValidateIdStringRequest() {
        }
        
        public ValidateIdStringRequest(string authToken, string said) {
            this.authToken = authToken;
            this.said = said;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidateIdStringResponse", WrapperNamespace="http://xml-fx.com/services/SAIDValidator/", IsWrapped=true)]
    public partial class ValidateIdStringResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xml-fx.com/services/SAIDValidator/said.xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://xml-fx.com/services/SAIDValidator/said.xsd")]
        public IDGenerator.SaIDValidator.saidType said;
        
        public ValidateIdStringResponse() {
        }
        
        public ValidateIdStringResponse(IDGenerator.SaIDValidator.saidType said) {
            this.said = said;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SAIDValidatorSoapChannel : IDGenerator.SaIDValidator.SAIDValidatorSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SAIDValidatorSoapClient : System.ServiceModel.ClientBase<IDGenerator.SaIDValidator.SAIDValidatorSoap>, IDGenerator.SaIDValidator.SAIDValidatorSoap {
        
        public SAIDValidatorSoapClient() {
        }
        
        public SAIDValidatorSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SAIDValidatorSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SAIDValidatorSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SAIDValidatorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetServiceIdentifier() {
            return base.Channel.GetServiceIdentifier();
        }
        
        public System.Threading.Tasks.Task<string> GetServiceIdentifierAsync() {
            return base.Channel.GetServiceIdentifierAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IDGenerator.SaIDValidator.ValidateIdStringResponse IDGenerator.SaIDValidator.SAIDValidatorSoap.ValidateIdString(IDGenerator.SaIDValidator.ValidateIdStringRequest request) {
            return base.Channel.ValidateIdString(request);
        }
        
        public IDGenerator.SaIDValidator.saidType ValidateIdString(string authToken, string said) {
            IDGenerator.SaIDValidator.ValidateIdStringRequest inValue = new IDGenerator.SaIDValidator.ValidateIdStringRequest();
            inValue.authToken = authToken;
            inValue.said = said;
            IDGenerator.SaIDValidator.ValidateIdStringResponse retVal = ((IDGenerator.SaIDValidator.SAIDValidatorSoap)(this)).ValidateIdString(inValue);
            return retVal.said;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IDGenerator.SaIDValidator.ValidateIdStringResponse> IDGenerator.SaIDValidator.SAIDValidatorSoap.ValidateIdStringAsync(IDGenerator.SaIDValidator.ValidateIdStringRequest request) {
            return base.Channel.ValidateIdStringAsync(request);
        }
        
        public System.Threading.Tasks.Task<IDGenerator.SaIDValidator.ValidateIdStringResponse> ValidateIdStringAsync(string authToken, string said) {
            IDGenerator.SaIDValidator.ValidateIdStringRequest inValue = new IDGenerator.SaIDValidator.ValidateIdStringRequest();
            inValue.authToken = authToken;
            inValue.said = said;
            return ((IDGenerator.SaIDValidator.SAIDValidatorSoap)(this)).ValidateIdStringAsync(inValue);
        }
    }
}
